#!/bin/bash
#PBS -l walltime=0:30:00
#PBS -N fslDTIFIT

module load singularity 2> /dev/null

#set -e

# extract shell if necessary
if [[ ${multishell} == false ]]; then
	echo "extract shell for tensor fit"
	time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./extractShells.sh
fi

# fit tensor
echo "dti fit"
time singularity exec -e docker://brainlife/fsl:5.0.11 ./fslDTIFIT.sh

if [ -f fa.nii.gz ];
then
	echo 0 > finished
else
	echo "output missing"
	echo 1 > finished
fi
